version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"

    # Labels for pull requests
    labels:
      - "dependencies"
      - "npm"
      - "automerge"

    # Maximum number of open PRs
    open-pull-requests-limit: 10

    # Pull request settings
    pull-request-branch-name:
      separator: "-"

    # Commit message settings
    commit-message:
      prefix: "chore"
      include: "scope"

    # Version update strategy
    versioning-strategy: auto

    # Allow both direct and indirect updates
    allow:
      - dependency-type: "all"

    # Group dependencies in PRs
    groups:
      # Production dependencies
      production:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      # Development dependencies
      development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      # Major updates in separate group
      major-updates:
        update-types:
          - "major"
